"[#] ci/cd":
 - '.github/*'
 - '.github/**/*'

"[#] deps":
 - 'go.mod'
 - 'go.sum'

"[#] doc":
 - '*.md'
 - 'doc/*'
 - 'doc/**/*'
 - 'examples/**/*'

"[#] app":
 - '*.go'
 - 'internal/*'
 - 'internal/**/*'
